agent {
	trust_domain = "example.org"
	server_address = "spireServer"
	server_port = 8081
	socket_path = "/opt/spire/sockets/agent.sock"
	log_level = "INFO"
    insecure_bootstrap = true
	allow_unauthenticated_verifiers = true
}

plugins {
	NodeAttestor "join_token" {
		plugin_data {}
	}
	WorkloadAttestor "docker" {
		plugin_data {
			docker_socket_path = "unix:///var/run/docker.sock"
		}
	}
	KeyManager "disk" {
		plugin_data {
			directory = "/var/lib/spire"
		}
	}
}